1_Acinetobacter_baumannii_J9:
  R1:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Acinetobacter_baumannii_J9/Acinetobacter_baumannii_J9_R1.fastq.gz
  R2:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Acinetobacter_baumannii_J9/Acinetobacter_baumannii_J9_R2.fastq.gz
2_Citrobacter_koseri_MINF_9D:
  R1:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Citrobacter_koseri_MINF_9D/Citrobacter_koseri_MINF_9D_R1.fastq.gz
  R2:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Citrobacter_koseri_MINF_9D/Citrobacter_koseri_MINF_9D_R2.fastq.gz
3_Enterobacter_kobei_MSB1_1B:
  R1:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Enterobacter_kobei_MSB1_1B/Enterobacter_kobei_MSB1_1B_R1.fastq.gz
  R2:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Enterobacter_kobei_MSB1_1B/Enterobacter_kobei_MSB1_1B_R2.fastq.gz
4_Haemophilus_unknown_M1C132_1:
  R1:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Haemophilus_unknown_M1C132_1/Haemophilus_unknown_M1C132_1_R1.fastq.gz
  R2:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Haemophilus_unknown_M1C132_1/Haemophilus_unknown_M1C132_1_R2.fastq.gz
5_Klebsiella_oxytoca_MSB1_2C:
  R1:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Klebsiella_oxytoca_MSB1_2C/Klebsiella_oxytoca_MSB1_2C_R1.fastq.gz
  R2:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Klebsiella_oxytoca_MSB1_2C/Klebsiella_oxytoca_MSB1_2C_R2.fastq.gz
6_CHF10J1.guppy5.sup:
  R1:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Salmonella_isangi_17-762-33892/17762-33892_1_71_bbduk_1.fastq.gz
  R2:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Salmonella_isangi_17-762-33892/17762-33892_1_71_bbduk_2.fastq.gz
7_Klebsiella_variicola_INF345:
  R1:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Klebsiella_variicola_INF345/Klebsiella_variicola_INF345_R1.fastq.gz
  R2:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Klebsiella_variicola_INF345/Klebsiella_variicola_INF345_R2.fastq.gz
8_Serratia_marcescens_17-147-1671:
  R1:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Serratia_marcescens_17-147-1671/Serratia_marcescens_17-147-1671_R1.fastq.gz
  R2:
    /home/ubuntu/data/belson/Guppy5_guppy3_comparison/input_data/clean_illumina_reads/Serratia_marcescens_17-147-1671/Serratia_marcescens_17-147-1671_R2.fastq.gz

samples: [1_Acinetobacter_baumannii_J9,2_Citrobacter_koseri_MINF_9D,3_Enterobacter_kobei_MSB1_1B,4_Haemophilus_unknown_M1C132_1,5_Klebsiella_oxytoca_MSB1_2C,6_CHF10J1.guppy5.sup,7_Klebsiella_variicola_INF345,8_Serratia_marcescens_17-147-1671]

to_run: /home/ubuntu/data/belson/bioinformatics/projects_2021/napa/input_data/guppy_5
results: 
  /home/ubuntu/data/belson/projects/projects_2021/napa/results/2021.08.23/guppy5

model:
  r941_min_sup_g507

# Environments

flye:
  /home/ubuntu/data/belson/Guppy5_guppy3_comparison/napa/scripts/envs/flye.yml

medaka:
  /home/ubuntu/data/belson/isangi_nanopore/scripts/envs/medaka.yml